# Minimal starship config for versionzero
add_newline = false

[directory]
read_only = "ğŸ”’"
style = "cyan"

[job]
threshold = 5

[character]
success_symbol = "â¯"
error_symbol = "âœ–"
style = "bold green"
